# Generated by Django 2.2.12 on 2020-06-11 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kname', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktitle', models.CharField(max_length=50)),
                ('etitle', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=70)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('adult', models.BooleanField()),
                ('koverview', models.TextField()),
                ('eoverview', models.TextField()),
                ('original_language', models.CharField(max_length=20)),
                ('poster_path', models.CharField(max_length=50)),
                ('backdrop_path', models.CharField(max_length=50)),
                ('genres', models.ManyToManyField(related_name='in_movies', to='movies.Genre')),
                ('liked_users', models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeduser', to='movies.Genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedgenre', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
