# Generated by Django 2.2.12 on 2020-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trendingdate', models.DateField(auto_now=True)),
                ('movies', models.ManyToManyField(related_name='istrending', to='movies.Movie')),
            ],
        ),
    ]
