# Generated by Django 2.2.12 on 2020-06-13 06:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('movies', '0005_auto_20200611_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
