# Generated by Django 2.2.12 on 2020-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='trendingdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
