# Generated by Django 2.2.12 on 2020-06-13 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200613_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_counter',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='genre_counter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='gender_age_counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('ages', models.CharField(choices=[('10', '20살 미만'), ('20', '20대'), ('30', '30대'), ('40', '40대'), ('50', '50대 이상')], max_length=2)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
    ]
