# Generated by Django 2.2.12 on 2020-06-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20200613_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender_age_counter',
            old_name='movies',
            new_name='movie',
        ),
    ]
