# Generated by Django 2.2.12 on 2020-06-13 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200613_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
