# Generated by Django 2.2.12 on 2020-06-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_report_reported_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='isresolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='simple_reason',
            field=models.CharField(choices=[('욕', '욕설'), ('어그로', '불쾌함을 주는 말'), ('외설', '외설적인 표현'), ('기타', '기타')], max_length=10),
        ),
    ]
